# permissions for end users to edit nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-editor-role
rules:
- apiGroups:
  - k8s.alicey.dev
  resources:
  - nginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.alicey.dev
  resources:
  - nginxes/status
  verbs:
  - get
